# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:
  # Build and push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'compose'
      - 'build'
      - '--parallel'
  
  # Deploy using Docker Compose
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']

images:
  - 'gcr.io/$solidmetaprediction/annoy_script@latest'
